### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ivanafanasyeu** [danileao/vscode-css-variables-autocomplete#2]
- Issue Type: `Performance`
- Extension Name: `css-variables-autocomplete`
- Extension Version: `0.0.3`
- OS Version: `Darwin x64 19.6.0`
- VSCode version: `1.51.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/var/folders/wm/9gdd0xys75n7phjsprkcy_cm0000gn/T/danileao.css-variables-autocomplete-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by wesbos** [comment]
yeah I tried using this and it kept causing my extension host to crash

**Comment by phoenisx** [comment]
Hi @wesbos @ivanafanasyev 

You can try this plugin https://marketplace.visualstudio.com/items?itemName=phoenisx.cssvar, and share the feedback

**Comment by ivanafanasyeu** [comment]
due to inactivity
